### ISSUE TITLE
Add possibility to change icon size

### ISSUE THREAD

**Issue by Millennium-bug-82** [iantrich/radial-menu#20]
Would it be possible to add an option to change the size of the icons?

**Comment by iantrich** [comment]
Added in https://github.com/iantrich/radial-menu/releases/tag/1.6.0

**Comment by micahriley88** [comment]
> Added in https://github.com/iantrich/radial-menu/releases/tag/1.6.0

When I adjust "radial-icon-size", the background circle created within _radial-menu.js > .menu-button > height & width_'s values should remain proportionally higher. Otherwise, the circle remains the same size (24px) and off-center. 

If I'm doing everything correctly, perhaps radial-icon-size could be referenced within your inline styling with +20% of that value for .menu-button's height and width?

EDIT: Looks like line-height should be adjusted to the same as width and height. Instead of +20%, it would be better to use the same value as _radial-icon-size_'s

(Love your project by the way! Thanks!)
